"""
agents/context_exporter.py
Sprint 4: Exports the knowledge graph as portable context for any AI tool.
Formats: prompt (plaintext), markdown, JSON, CSV.
"""
import json
import csv
import io
from core.graph_engine import GraphEngine


class ContextExporter:
    def __init__(self, graph: GraphEngine):
        self.graph = graph

    def stats(self) -> dict:
        sm = self.graph.summary()
        return {
            "total_nodes": sm["total_nodes"],
            "total_edges": sm["total_edges"],
            "by_type": sm["nodes_by_type"],
            "nm_graph": sm["nm_graph"],
        }

    def to_prompt(self) -> str:
        """Generate a system prompt block usable in any AI tool."""
        lines = [
            "=== ORGANIZATIONAL CONTEXT (generated by Knowledge Harness) ===",
            "",
        ]

        section_map = {
            "brand": "BRAND IDENTITY",
            "audience": "TARGET AUDIENCES",
            "value": "CORE VALUES",
            "tone": "TONE & VOICE GUIDELINES",
            "restrict": "PROHIBITIONS (NEVER DO)",
            "example": "REFERENCE EXAMPLES",
        }

        for ntype, title in section_map.items():
            nodes = self.graph.get_nodes(node_type=ntype)
            if not nodes:
                continue
            lines.append(f"## {title}")
            for n in nodes:
                stability_mark = " [!]" if n["stability"] == "flagged" else ""
                lines.append(f"- {n['label']}{stability_mark}: {n['detail']}")
            lines.append("")

        # Append edges as relationship summary
        edges = self.graph._edges
        if edges:
            lines.append("## KEY RELATIONSHIPS")
            for e in edges[:20]:
                fn = self.graph.get_node(e["from"])
                tn = self.graph.get_node(e["to"])
                if fn and tn:
                    lines.append(f"- {fn['label']} {e['relation']} {tn['label']}")
            lines.append("")

        nm = self.graph.nm_graph()
        if nm.get("nm") is not None:
            lines.append(f"[NM_graph stability: {nm['nm']:.3f} — {nm['state'].upper()}]")

        return "\n".join(lines)

    def to_markdown(self) -> str:
        """Generate structured Markdown for documentation."""
        lines = ["# Organizational Knowledge Graph\n"]

        section_map = {
            "brand": "Brand Identity",
            "audience": "Target Audiences",
            "value": "Core Values",
            "tone": "Tone & Voice",
            "restrict": "Prohibitions",
            "example": "Examples",
        }

        for ntype, title in section_map.items():
            nodes = self.graph.get_nodes(node_type=ntype)
            if not nodes:
                continue
            lines.append(f"## {title}\n")
            for n in nodes:
                stability_badge = f" `{n['stability']}`" if n["stability"] != "stable" else ""
                lines.append(f"### {n['label']}{stability_badge}")
                lines.append(f"{n['detail']}\n")

        nm = self.graph.nm_graph()
        if nm.get("nm") is not None:
            lines.append(f"---\n*NM_graph: {nm['nm']:.3f} ({nm['state']})*")

        return "\n".join(lines)

    def to_json(self, include_evidence: bool = False) -> str:
        data = {
            "nodes": list(self.graph._nodes.values()),
            "edges": self.graph._edges,
            "nm_graph": self.graph.nm_graph(),
            "summary": self.graph.summary(),
        }
        if include_evidence:
            data["evidence"] = self.graph._evidence
            data["proposals"] = self.graph._proposals
        return json.dumps(data, ensure_ascii=False, indent=2)

    def to_csv(self) -> str:
        output = io.StringIO()
        writer = csv.DictWriter(
            output,
            fieldnames=["id", "type", "label", "detail", "stability", "source", "created_at"],
        )
        writer.writeheader()
        for n in self.graph._nodes.values():
            writer.writerow({k: n.get(k, "") for k in writer.fieldnames})
        return output.getvalue()