"""
Proposal Queue — Organizational Knowledge Harness Sprint 2
Manages the lifecycle of graph update proposals.

States: pending → approved | rejected | deferred
"""

from datetime import datetime, timezone
from core.graph_engine import GraphEngine


class ProposalQueue:
    """
    Manages proposals generated by the Evidence Accumulator.
    Human approval required before any change is written to the graph.
    """

    def __init__(self, graph: GraphEngine):
        self.graph = graph

    # -----------------------------------------------------------------------
    # Read
    # -----------------------------------------------------------------------

    def pending(self) -> list[dict]:
        return [p for p in self.graph._proposals if p.get("status") == "pending"]

    def all(self) -> list[dict]:
        return list(self.graph._proposals)

    def get(self, proposal_id: str) -> dict | None:
        for p in self.graph._proposals:
            if p["id"] == proposal_id:
                return p
        return None

    # -----------------------------------------------------------------------
    # Actions
    # -----------------------------------------------------------------------

    def approve(self, proposal_id: str) -> dict:
        """
        Approve a proposal — writes the suggested change to the graph.
        Clears related signals. Commits to git.
        """
        proposal = self._find_pending(proposal_id)
        change = proposal.get("suggested_change")

        if change:
            node_id = proposal["node_id"]
            field = change["field"]
            value = change["suggested"]
            self.graph.update_node(node_id, {field: value})

        self._resolve(proposal, "approved")
        self._clear_signals(proposal["node_id"], proposal["signal_type"])

        self.graph.save(
            f"approved: {proposal['proposal_type']} on '{proposal['node_label']}' "
            f"— {proposal['signal_count']} signals"
        )
        return proposal

    def reject(self, proposal_id: str) -> dict:
        """
        Reject a proposal — discards signals, marks node stable for N cycles.
        """
        proposal = self._find_pending(proposal_id)
        self._resolve(proposal, "rejected")
        self._clear_signals(proposal["node_id"], proposal["signal_type"])

        # Mark node as stable to suppress re-proposals for a while
        try:
            self.graph.update_node(proposal["node_id"], {"stability": "stable"})
        except KeyError:
            pass

        self.graph.save(
            f"rejected: {proposal['proposal_type']} on '{proposal['node_label']}'"
        )
        return proposal

    def defer(self, proposal_id: str) -> dict:
        """
        Defer a proposal — keeps signals, moves proposal to deferred state.
        """
        proposal = self._find_pending(proposal_id)
        self._resolve(proposal, "deferred")
        self.graph.save(
            f"deferred: {proposal['proposal_type']} on '{proposal['node_label']}'"
        )
        return proposal

    # -----------------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------------

    def _find_pending(self, proposal_id: str) -> dict:
        proposal = self.get(proposal_id)
        if not proposal:
            raise KeyError(f"Proposal not found: {proposal_id}")
        if proposal["status"] != "pending":
            raise ValueError(f"Proposal {proposal_id} is not pending (status: {proposal['status']})")
        return proposal

    def _resolve(self, proposal: dict, status: str):
        proposal["status"] = status
        proposal["resolved_at"] = datetime.now(timezone.utc).isoformat()

    def _clear_signals(self, node_id: str, signal_type: str):
        """Remove accumulated signals for this node+signal_type combination."""
        self.graph._evidence = [
            s for s in self.graph._evidence
            if not (s["node_id"] == node_id and s["signal_type"] == signal_type)
        ]

    def stats(self) -> dict:
        all_proposals = self.all()
        by_status: dict[str, int] = {}
        for p in all_proposals:
            s = p.get("status", "unknown")
            by_status[s] = by_status.get(s, 0) + 1
        return {
            "total": len(all_proposals),
            "by_status": by_status,
            "pending": by_status.get("pending", 0),
        }
